from __future__ import annotations

from dataclasses import dataclass
from datetime import date
import hashlib
import json
import math
from pathlib import Path

import numpy as np

from .shapes import (
    Stroke,
    arc_points,
    circle_points,
    polyline_points,
    star_points,
    triangle_points,
    wave_points,
)


@dataclass(frozen=True)
class DrawingPlan:
    """A semantic plan before it is compiled to robot tool targets."""

    title: str
    reading: str
    interpretation: str
    symbols: list[dict[str, str]]
    strokes: list[Stroke]


def plan_from_text(prompt: str, today: date | None = None, seed_text: str | None = None) -> DrawingPlan:
    """Turn natural language into a deterministic drawing plan.

    This is intentionally local and hackathon-friendly: no API key is needed.
    By default the same prompt on the same date produces the same picture.
    Pass `seed_text` when a caller wants per-request visual variation.
    """
    current_day = today or date.today()
    text = prompt.strip()
    lower = text.lower()
    seed_source = seed_text if seed_text is not None else text
    seed = _stable_seed(f"{current_day.isoformat()}:{seed_source}")
    score = seed % 100

    if _has_any(lower, ["fortune", "运势", "星座", "占卜", "好运", "today"]):
        return _fortune_plan(score, current_day)
    if _has_any(lower, ["triangle", "三角"]):
        return DrawingPlan(
            title="triangle",
            reading="A steady triangle: focus, structure, and forward motion.",
            interpretation="这张图可以理解为稳定的三角结构：先定目标，再分步骤推进。",
            symbols=[{"name": "triangle", "meaning": "structure and focus"}],
            strokes=[triangle_points(center=(0.02, 0.0), side=0.2)],
        )
    if _has_any(lower, ["circle", "圆"]):
        return DrawingPlan(
            title="circle",
            reading="A clear circle: continuity, calm, and completion.",
            interpretation="这张图可以理解为一个闭环：今天适合收尾、复盘和把事情整理完整。",
            symbols=[{"name": "circle", "meaning": "completion and calm"}],
            strokes=[circle_points(center=(0.0, 0.0), radius=0.1)],
        )

    return _abstract_plan(score)


def toolpath_payload_from_text(
    prompt: str,
    draw_z: float = 0.018,
    travel_z: float = 0.09,
    spacing: float = 0.005,
    today: date | None = None,
    seed_text: str | None = None,
) -> dict:
    """Compile natural language into a robot-parseable trajectory payload."""
    plan = plan_from_text(prompt, today=today, seed_text=seed_text)
    if plan.title == "today_fortune":
        spacing = max(spacing, 0.028)
    strokes = [stroke.with_lift(draw_z=draw_z, travel_z=travel_z) for stroke in plan.strokes]
    path = _interpolate_strokes(strokes, spacing=spacing)
    return {
        "format": "piper_toolpath_v1",
        "units": "meters",
        "frame": "canvas",
        "draw_z": draw_z,
        "travel_z": travel_z,
        "title": plan.title,
        "reading": plan.reading,
        "interpretation": plan.interpretation,
        "symbols": plan.symbols,
        "points": np.round(path, 6).tolist(),
    }


def toolpath_payload_from_strokes(
    strokes_xy: list[list[list[float]]],
    title: str,
    reading: str,
    interpretation: str,
    symbols: list[dict[str, str]] | None = None,
    draw_z: float = 0.018,
    travel_z: float = 0.09,
) -> dict:
    """Build a robot payload from raw XY strokes generated by the LLM."""
    from .shapes import polyline_points
    import numpy as np
    valid = [s for s in strokes_xy if len(s) >= 2]
    strokes = [polyline_points([(float(p[0]), float(p[1])) for p in s]) for s in valid]
    path_strokes = [stroke.with_lift(draw_z=draw_z, travel_z=travel_z) for stroke in strokes]
    path = np.vstack(path_strokes) if path_strokes else np.zeros((0, 3), dtype=float)
    return {
        "format": "piper_toolpath_v1",
        "units": "meters",
        "frame": "canvas",
        "draw_z": draw_z,
        "travel_z": travel_z,
        "title": title,
        "reading": reading,
        "interpretation": interpretation,
        "symbols": symbols or [],
        "points": np.round(path, 6).tolist(),
    }


def write_toolpath_json(payload: dict, output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def strokes_from_payload(payload: dict) -> list[np.ndarray]:
    """Read a robot payload back into simulator strokes."""
    points = np.asarray(payload["points"], dtype=float)
    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError("payload points must be shaped (N, 3)")
    return [points]


def _fortune_plan(score: int, today: date) -> DrawingPlan:
    energy = 55 + score % 41
    opportunity = 45 + ((score * 7) % 51)
    emotion = 40 + ((score * 11) % 56)
    caution = 25 + ((score * 5) % 46)
    variant = score % 4

    taiji_radius = 0.072 + 0.00022 * (energy - 55)
    seal_size = 0.058 + 0.00018 * opportunity

    strokes = [
        *_taiji_mark(center=_variant_point(variant, "taiji"), radius=taiji_radius),
        *_trigram_mark(
            origin=_variant_point(variant, "trigram"),
            width=0.115 + 0.00045 * opportunity,
            gap=0.026 + 0.00006 * caution,
            broken=score % 2 == 0,
        ),
        *_talisman_mark(
            center=_variant_point(variant, "talisman"),
            height=0.162 + 0.00042 * energy,
            width=seal_size,
        ),
    ]
    level = "偏旺" if score >= 67 else "平稳上升" if score >= 34 else "温和蓄力"
    best_window = "日光初明时" if opportunity >= 72 else "午后气缓时" if emotion >= 70 else "暮色未沉时"
    action = "定心而后言，择一事轻轻推开" if opportunity >= 70 else "收束杂念，守住一线清明"
    caution_text = "忌躁进，忌临时起意" if caution >= 50 else "宜留余白，宜慢半拍"
    reading = (
        f"{today.isoformat()} 今日玄运：{level}。"
        "阴阳相抱，机缘藏于静处；先守中线，再顺势开门。"
    )
    interpretation = (
        "这张玄运图只留三个主元素，看气势，不逐项报数。太极印为底盘，阴阳相抱，表示今日宜先安内，"
        "再向外行事；三爻卦为机缘门，线有连断，说明机会不是直落掌心，而要顺着缝隙进入；"
        "中央符箓为行动轴，竖线定心，折笔开路，像一道先收后放的符令，提醒言语和决定都不宜太急，"
        f"{caution_text}。若要取用此图，可在{best_window}行一件小而明确的事：{action}。"
    )
    symbols = [
        {"name": "taiji_seal", "meaning": "yin-yang baseline"},
        {"name": "three_line_hexagram", "meaning": "opportunity hidden in timing"},
        {"name": "talisman_axis", "meaning": "settle first, then open the path"},
    ]
    return DrawingPlan(
        title="today_fortune",
        reading=reading,
        interpretation=interpretation,
        symbols=symbols,
        strokes=strokes,
    )


def _abstract_plan(score: int) -> DrawingPlan:
    radius = 0.095 + 0.0004 * (score % 40)
    strokes = [
        circle_points(center=(-0.09, 0.02), radius=radius, samples=96),
        triangle_points(center=(0.115, -0.005), side=0.19),
        wave_points(start=(-0.18, -0.115), width=0.36, amplitude=0.026, cycles=1.7),
    ]
    return DrawingPlan(
        title="abstract_response",
        reading="An abstract response: balance, motion, and a simple next step.",
        interpretation="这张抽象图可以从左到右读：圆代表整理状态，三角代表行动结构，波浪代表情绪节奏。",
        symbols=[
            {"name": "circle", "meaning": "state"},
            {"name": "triangle", "meaning": "action"},
            {"name": "wave", "meaning": "rhythm"},
        ],
        strokes=strokes,
    )


def _sun_rays(center: tuple[float, float], radius: float) -> list[Stroke]:
    rays = []
    for angle in np.linspace(0.0, 2.0 * math.pi, 8, endpoint=False):
        inner = (center[0] + radius * math.cos(angle), center[1] + radius * math.sin(angle))
        outer = (
            center[0] + (radius + 0.026) * math.cos(angle),
            center[1] + (radius + 0.026) * math.sin(angle),
        )
        rays.append(polyline_points([inner, outer]))
    return rays


def _straight_taiji_mark(center: tuple[float, float], radius: float) -> list[Stroke]:
    x, y = center
    return [
        _diamond_points(center=center, radius=radius),
        polyline_points([(x, y + radius), (x, y - radius)]),
        polyline_points([(x - radius * 0.55, y + radius * 0.24), (x + radius * 0.55, y + radius * 0.24)]),
        polyline_points([(x - radius * 0.55, y - radius * 0.24), (x + radius * 0.55, y - radius * 0.24)]),
        _diamond_points(center=(x, y + radius * 0.47), radius=radius * 0.13),
        _diamond_points(center=(x, y - radius * 0.47), radius=radius * 0.13),
    ]


def _taiji_mark(center: tuple[float, float], radius: float) -> list[Stroke]:
    return [
        circle_points(center=center, radius=radius, samples=112),
        arc_points(center=(center[0], center[1] + radius / 2.0), radius=radius / 2.0,
                   start_angle=-math.pi / 2.0, end_angle=math.pi / 2.0, samples=42),
        arc_points(center=(center[0], center[1] - radius / 2.0), radius=radius / 2.0,
                   start_angle=math.pi / 2.0, end_angle=3.0 * math.pi / 2.0, samples=42),
        circle_points(center=(center[0], center[1] + radius / 2.0), radius=radius * 0.12, samples=28),
        circle_points(center=(center[0], center[1] - radius / 2.0), radius=radius * 0.12, samples=28),
    ]


def _diamond_points(center: tuple[float, float], radius: float) -> Stroke:
    x, y = center
    return polyline_points(
        [(x, y + radius), (x + radius, y), (x, y - radius), (x - radius, y)],
        closed=True,
    )


def _zigzag_wave_points(
    start: tuple[float, float],
    width: float,
    amplitude: float = 0.018,
    cycles: float = 2.0,
) -> Stroke:
    if width <= 0:
        raise ValueError("width must be positive")
    steps = max(6, int(round(cycles * 4)))
    points = []
    for index in range(steps + 1):
        x = start[0] + width * index / steps
        if index == 0 or index == steps:
            y = start[1]
        else:
            y = start[1] + (amplitude if index % 2 else -amplitude)
        points.append((x, y))
    return polyline_points(points)


def _angled_arc_points(
    center: tuple[float, float],
    radius: float,
    start_angle: float,
    end_angle: float,
) -> Stroke:
    if radius <= 0:
        raise ValueError("radius must be positive")
    samples = 6
    theta = np.linspace(start_angle, end_angle, samples)
    points = [
        (center[0] + radius * math.cos(angle), center[1] + radius * math.sin(angle))
        for angle in theta
    ]
    return polyline_points(points)


def _trigram_mark(
    origin: tuple[float, float],
    width: float,
    gap: float,
    broken: bool,
) -> list[Stroke]:
    strokes = []
    y_values = [origin[1], origin[1] - gap, origin[1] - 2.0 * gap]
    for index, y in enumerate(y_values):
        should_break = broken and index == 1
        if should_break:
            strokes.append(polyline_points([(origin[0], y), (origin[0] + width * 0.38, y)]))
            strokes.append(polyline_points([(origin[0] + width * 0.62, y), (origin[0] + width, y)]))
        else:
            strokes.append(polyline_points([(origin[0], y), (origin[0] + width, y)]))
    return strokes


def _talisman_mark(center: tuple[float, float], height: float, width: float) -> list[Stroke]:
    x, y = center
    top = y + height / 2.0
    bottom = y - height / 2.0
    return [
        polyline_points([(x, top), (x, bottom)]),
        polyline_points([(x - width, top - 0.012), (x, top), (x + width, top - 0.012)]),
        polyline_points([(x - width * 0.75, top - 0.045), (x + width * 0.75, top - 0.045)]),
        polyline_points([(x - width * 0.65, y + 0.005), (x + width * 0.65, y - 0.015)]),
        polyline_points([(x + width * 0.45, y + 0.03), (x - width * 0.2, y - 0.04), (x + width * 0.55, y - 0.075)]),
        polyline_points([(x - width * 0.8, bottom + 0.018), (x, bottom), (x + width * 0.8, bottom + 0.018)]),
    ]


def _variant_point(variant: int, name: str) -> tuple[float, float]:
    layouts = [
        {
            "taiji": (-0.125, 0.058),
            "trigram": (0.075, 0.108),
            "talisman": (0.02, 0.012),
            "wave": (-0.185, -0.105),
            "arc": (-0.02, -0.064),
            "caution": (0.165, -0.072),
            "star": (0.145, 0.025),
        },
        {
            "taiji": (0.122, 0.052),
            "trigram": (-0.18, 0.11),
            "talisman": (-0.015, 0.006),
            "wave": (-0.17, -0.112),
            "arc": (0.035, -0.058),
            "caution": (-0.155, -0.064),
            "star": (0.155, -0.004),
        },
        {
            "taiji": (-0.05, 0.082),
            "trigram": (0.083, 0.01),
            "talisman": (-0.108, -0.018),
            "wave": (-0.178, -0.118),
            "arc": (0.078, -0.076),
            "caution": (0.158, 0.076),
            "star": (-0.168, 0.008),
        },
        {
            "taiji": (0.07, -0.02),
            "trigram": (-0.178, 0.086),
            "talisman": (0.108, 0.036),
            "wave": (-0.178, -0.096),
            "arc": (-0.082, -0.066),
            "caution": (0.166, -0.102),
            "star": (-0.018, 0.118),
        },
    ]
    return layouts[variant % len(layouts)][name]


def _variant_caution_line(variant: int) -> list[tuple[float, float]]:
    x, y = _variant_point(variant, "caution")
    if variant % 2 == 0:
        return [(x, y - 0.027), (x, y + 0.02)]
    return [(x - 0.023, y), (x + 0.023, y)]


def _variant_extra_marks(variant: int, score: int) -> list[Stroke]:
    if variant == 0:
        return _sun_rays(center=(0.0, 0.12), radius=0.018 + 0.00008 * score)
    if variant == 1:
        return [
            _diamond_points(center=(-0.012, 0.112), radius=0.025),
            _angled_arc_points(center=(-0.004, 0.116), radius=0.024, start_angle=1.55, end_angle=4.7),
        ]
    if variant == 2:
        return [
            triangle_points(center=(0.02, 0.118), side=0.052, rotation=math.pi / 2.0),
            polyline_points([(-0.006, 0.108), (0.02, 0.138), (0.046, 0.108)]),
        ]
    return [
        _zigzag_wave_points(start=(-0.036, 0.124), width=0.082, amplitude=0.008, cycles=1.3),
        polyline_points([(-0.042, 0.1), (0.0, 0.137), (0.044, 0.1)]),
    ]


def _interpolate_strokes(strokes: list[np.ndarray], spacing: float) -> np.ndarray:
    from .shapes import interpolate_polyline

    if not strokes:
        return np.zeros((0, 3), dtype=float)
    return interpolate_polyline(np.vstack(strokes), spacing=spacing)


def _stable_seed(text: str) -> int:
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return int(digest[:8], 16)


def _has_any(text: str, needles: list[str]) -> bool:
    return any(needle in text for needle in needles)
